# This workflow will do a clean install of node dependencies, build the project, generate the API documentation and publish it th GitHub pages

name: Deploy the API documentation for Bubanai

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name wix-deploy
          git config --global user.email wix-deploy@wix.com
          git remote set-url origin https://${github_token}@github.com/${repository}
          yarn deploy

        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
